version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: gameshelf_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: gameshelf_backend
    ports:
       - "4001:4000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/gameshelf
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: gameshelf_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  